# Generated by Django 6.0.4 on 2026-04-22 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=200)),
                ("brand", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Shoes", "Shoes"),
                            ("Clothing", "Clothing"),
                            ("Outerwear", "Outerwear"),
                            ("Handbag", "Handbag"),
                            ("Accessory", "Accessory"),
                            ("Jewelry", "Jewelry"),
                            ("Makeup", "Makeup"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("size", models.CharField(blank=True, max_length=50, null=True)),
                ("color", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Like New", "Like New"),
                            ("Good", "Good"),
                            ("Fair", "Fair"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("acquired_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Keeping", "Keeping"),
                            ("Listed", "Listed"),
                            ("Sold", "Sold"),
                        ],
                        default="Keeping",
                        max_length=20,
                    ),
                ),
                (
                    "listing_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "sold_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Depop", "Depop"),
                            ("Poshmark", "Poshmark"),
                            ("Mercari", "Mercari"),
                            ("eBay", "eBay"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("sold_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ItemTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.item"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tag"
                    ),
                ),
            ],
            options={
                "unique_together": {("item", "tag")},
            },
        ),
    ]
